### ISSUE TITLE
Failed to link

### ISSUE THREAD

**Issue by Dialga** [samhh/bukubrow-host#30] opened 2020-12-25 14:18 UTC
```
   Compiling bukubrow v5.1.0 (/home/me/yay/bukubrow/src/bukubrow-host-5.1.0)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/buku/database.rs:85:39
   |
85 |                         &bm.flags as &ToSql,
   |                                       ^^^^^ help: use `dyn`: `dyn ToSql`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> src/buku/database.rs:101:42
    |
101 |                         &bm.metadata as &ToSql,
    |                                          ^^^^^ help: use `dyn`: `dyn ToSql`

error: linking with `cc` failed: exit code: 1
  |

.... whole bunch of errors

          collect2: error: ld returned 1 exit status

error: aborting due to previous error; 2 warnings emitted

error: could not compile `bukubrow`

To learn more, run the command again with --verbose.
```

**Comment by samhh** [comment] 2020-12-25 19:22
Which OS/distro are you on? Some cursory Googling suggests you're missing some build tooling for Rust.

**Comment by Dialga** [comment] 2020-12-25 20:33
```
$ uname -a; rustc -V
Linux archlinux 5.10.2-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 21 Dec 2020 19:59:37 +0000 x86_64 GNU/Linux
rustc 1.48.0
```

**Comment by samhh** [comment] 2020-12-26 14:50
As you're on Arch, do you have the [base-devel](https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites) group of packages installed?

**Comment by Dialga** [comment] 2020-12-26 15:10
yes everything in that group

**Comment by samhh** [comment] 2020-12-26 17:03
Can you compile other Rust projects? And what's the rest of the error message when you try to compile?

**Comment by Dialga** [comment] 2020-12-28 08:54
Every other rust project compiles for me.
```
   Compiling libc v0.2.43
   Compiling proc-macro2 v0.4.19
   Compiling pkg-config v0.3.14
   Compiling cc v1.0.25
   Compiling unicode-xid v0.1.0
   Compiling serde v1.0.79
   Compiling memchr v2.2.0
   Compiling ryu v0.2.6
   Compiling linked-hash-map v0.4.2
   Compiling cfg-if v0.1.5
   Compiling bitflags v1.0.4
   Compiling unicode-width v0.1.5
   Compiling byteorder v1.3.1
   Compiling itoa v0.4.3
   Compiling strsim v0.8.0
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.1
   Compiling fallible-iterator v0.2.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling webbrowser v0.5.1
   Compiling lru-cache v0.1.1
   Compiling textwrap v0.11.0
   Compiling dirs-sys v0.3.3
   Compiling atty v0.2.11
   Compiling time v0.1.40
   Compiling dirs v2.0.1
   Compiling clap v2.33.0
   Compiling quote v0.6.8
   Compiling libsqlite3-sys v0.15.0
   Compiling syn v0.15.6
   Compiling serde_json v1.0.30
   Compiling rusqlite v0.19.0
   Compiling serde_derive v1.0.79
   Compiling bukubrow v5.1.0 (/home/et/yay/bukubrow/src/bukubrow-host-5.1.0)
warning: trait objects without an explicit `dyn` are deprecated
  --> src/buku/database.rs:85:39
   |
85 |                         &bm.flags as &ToSql,
   |                                       ^^^^^ help: use `dyn`: `dyn ToSql`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
   --> src/buku/database.rs:101:42
    |
101 |                         &bm.metadata as &ToSql,
    |                                          ^^^^^ help: use `dyn`: `dyn ToSql`

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.0.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.1.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.10.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.11.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.12.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.13.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.14.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.15.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.2.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.3.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.4.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.5.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.6.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.7.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.8.rcgu.o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.bukubrow.134nvf97-cgu.9.rcgu.o" "-o" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/bukubrow-32f042749537baef.l16b6xbao6iofvi.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps" "-L" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/build/libsqlite3-sys-793c0b281d0f7d45/out" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libwebbrowser-e3a5d9b97a51c422.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libdirs-99216bc369ab512d.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libdirs_sys-0753cbf165a8e5bb.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libcfg_if-edbe6893c4852bd8.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libbyteorder-fd6d317ee233d3f1.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libclap-cad20b83a34c75c6.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libvec_map-a34a0cc7f6d20032.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libtextwrap-1f41e0af29b49df7.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libunicode_width-7d9d81bcd6f22d64.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libstrsim-b14aafdcfead8068.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libatty-c90b04fd589170d6.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libansi_term-8c7a2cb20e213251.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libmemchr-2b63548428e21497.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libtime-3f9f595b7380d334.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/liblibc-aa9570eb7406ae80.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libfallible_streaming_iterator-76a3aa192369efab.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libfallible_iterator-0481f00e7adc68ce.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/liblru_cache-d5867f027bb6a2b9.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/liblinked_hash_map-e3c9b42b2d9d7d33.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/liblibsqlite3_sys-b7baa711249f0e1e.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libbitflags-28234a10a5bddab6.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libserde_json-34d9bf5651b6e280.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libryu-c9e3ba532548aff1.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libitoa-86bb9d7652738a77.rlib" "/home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/libserde-0c6f0744e8a34729.rlib" "-Wl,--start-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-956fb6b91e7f20f6.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-14d16b002ff17197.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-7bf2f54b0cc54da6.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-d714adf67279f978.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-73dd0a4c58602a6b.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-7c54ed7e3523f4b7.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-555ad6ce28f3446a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-b6a8e0e99f403a8a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-5d0879d2298d56a3.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-7c09da6531c6e48a.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b0eb1308f130fee5.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-52efc174cb914f4b.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-b438cfcaca952612.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a582e8b8a1da98bd.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-6a630e97eb525188.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-61dd55c533489410.rlib" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b6ba48d363acaab0.rlib" "-Wl,-Bdynamic" "-lutil" "-lutil" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.10.rcgu.o): in function `_ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17hb8e1f95f66b8c5caE.llvm.2704780308060088436':
          rusqlite.dhl4v74x-cgu.10:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17hb8e1f95f66b8c5caE.llvm.2704780308060088436+0x1f): undefined reference to `sqlite3_config'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.10:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17hb8e1f95f66b8c5caE.llvm.2704780308060088436+0x29): undefined reference to `sqlite3_initialize'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.10.rcgu.o): in function `_ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2adb83e75d9a1303E.llvm.2704780308060088436':
          rusqlite.dhl4v74x-cgu.10:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2adb83e75d9a1303E.llvm.2704780308060088436+0x1f): undefined reference to `sqlite3_config'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.10:(.text._ZN4core3ops8function6FnOnce40call_once$u7b$$u7b$vtable.shim$u7d$$u7d$17h2adb83e75d9a1303E.llvm.2704780308060088436+0x29): undefined reference to `sqlite3_initialize'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.13.rcgu.o): in function `rusqlite::raw_statement::RawStatement::bind_parameter_count':
          rusqlite.dhl4v74x-cgu.13:(.text._ZN8rusqlite13raw_statement12RawStatement20bind_parameter_count17hec36ab184f37c8baE+0x6): undefined reference to `sqlite3_bind_parameter_count'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.13.rcgu.o): in function `<rusqlite::raw_statement::RawStatement as core::ops::drop::Drop>::drop':
          rusqlite.dhl4v74x-cgu.13:(.text._ZN79_$LT$rusqlite..raw_statement..RawStatement$u20$as$u20$core..ops..drop..Drop$GT$4drop17h2fcfa9b919e9dfb9E+0x9): undefined reference to `sqlite3_finalize'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.14.rcgu.o): in function `rusqlite::cache::StatementCache::flush':
          rusqlite.dhl4v74x-cgu.14:(.text._ZN8rusqlite5cache14StatementCache5flush17h3b0a179cb4e032e6E+0x3e): undefined reference to `sqlite3_finalize'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.2.rcgu.o): in function `rusqlite::error::error_from_handle':
          rusqlite.dhl4v74x-cgu.2:(.text._ZN8rusqlite5error17error_from_handle17h5370f2f706c658fcE+0x15): undefined reference to `sqlite3_errmsg'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::column::<impl rusqlite::statement::Statement>::column_count':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite6column48_$LT$impl$u20$rusqlite..statement..Statement$GT$12column_count17h858d870a6296ef11E+0x7): undefined reference to `sqlite3_column_count'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::column::<impl rusqlite::statement::Statement>::column_name':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite6column48_$LT$impl$u20$rusqlite..statement..Statement$GT$11column_name17h73b78943b8c25a5dE+0x17): undefined reference to `sqlite3_column_count'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite6column48_$LT$impl$u20$rusqlite..statement..Statement$GT$11column_name17h73b78943b8c25a5dE+0x26): undefined reference to `sqlite3_column_name'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::statement::Statement::bind_parameter':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x106): undefined reference to `sqlite3_bind_null'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x1d1): undefined reference to `sqlite3_bind_double'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x283): undefined reference to `sqlite3_bind_int64'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x2b4): undefined reference to `sqlite3_bind_blob'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x2cd): undefined reference to `sqlite3_bind_text'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement14bind_parameter17h909fe42eeb5427fbE+0x37f): undefined reference to `sqlite3_bind_zeroblob'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::statement::Statement::execute_with_bound_parameters':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement29execute_with_bound_parameters17h64f95a05bed008c3E+0x16): undefined reference to `sqlite3_step'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement29execute_with_bound_parameters17h64f95a05bed008c3E+0x22): undefined reference to `sqlite3_reset'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement29execute_with_bound_parameters17h64f95a05bed008c3E+0x36): undefined reference to `sqlite3_column_count'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement29execute_with_bound_parameters17h64f95a05bed008c3E+0x110): undefined reference to `sqlite3_changes'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `<rusqlite::statement::Statement as core::ops::drop::Drop>::drop':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN72_$LT$rusqlite..statement..Statement$u20$as$u20$core..ops..drop..Drop$GT$4drop17h5648bb152bc9e53eE+0x1a): undefined reference to `sqlite3_finalize'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::statement::Statement::value_ref':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0x1d): undefined reference to `sqlite3_column_type'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0x47): undefined reference to `sqlite3_column_int64'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0x61): undefined reference to `sqlite3_column_blob'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0x70): undefined reference to `sqlite3_column_bytes'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0x9b): undefined reference to `sqlite3_column_double'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement9value_ref17hec4e4da11cb178dbE+0xb4): undefined reference to `sqlite3_column_text'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.4.rcgu.o): in function `rusqlite::statement::Statement::step':
          rusqlite.dhl4v74x-cgu.4:(.text._ZN8rusqlite9statement9Statement4step17h8ee03df52b1de947E+0x15): undefined reference to `sqlite3_step'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.7.rcgu.o): in function `rusqlite::inner_connection::InnerConnection::open_with_flags':
          rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x15): undefined reference to `sqlite3_threadsafe'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x1f): undefined reference to `sqlite3_libversion_number'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x2e): undefined reference to `sqlite3_mutex_alloc'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x3a): undefined reference to `sqlite3_mutex_free'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0xba): undefined reference to `sqlite3_open_v2'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0xd7): undefined reference to `sqlite3_errmsg'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x128): undefined reference to `sqlite3_close'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x15e): undefined reference to `sqlite3_busy_timeout'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x17b): undefined reference to `sqlite3_errmsg'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x210): undefined reference to `sqlite3_extended_result_codes'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection15open_with_flags17h3e369af6ec2ca5a9E+0x2c9): undefined reference to `sqlite3_close'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.7.rcgu.o): in function `rusqlite::inner_connection::InnerConnection::close':
          rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection5close17hfc3e362a08fdf2e3E+0x77): undefined reference to `sqlite3_close'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection5close17hfc3e362a08fdf2e3E+0x8d): undefined reference to `sqlite3_errmsg'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.7.rcgu.o): in function `rusqlite::inner_connection::InnerConnection::prepare':
          rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection7prepare17h3bafb32929a2fbd0E+0x80): undefined reference to `sqlite3_prepare_v2'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.7:(.text._ZN8rusqlite16inner_connection15InnerConnection7prepare17h3bafb32929a2fbd0E+0x94): undefined reference to `sqlite3_errmsg'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.8.rcgu.o): in function `rusqlite::row::Rows::next':
          rusqlite.dhl4v74x-cgu.8:(.text._ZN8rusqlite3row4Rows4next17h6a798bd70dc19ee7E+0x7c): undefined reference to `sqlite3_reset'
          /usr/bin/ld: rusqlite.dhl4v74x-cgu.8:(.text._ZN8rusqlite3row4Rows4next17h6a798bd70dc19ee7E+0xfc): undefined reference to `sqlite3_reset'
          /usr/bin/ld: /home/et/yay/bukubrow/src/bukubrow-host-5.1.0/target/release/deps/librusqlite-b4835938f9b71da5.rlib(rusqlite-b4835938f9b71da5.rusqlite.dhl4v74x-cgu.8.rcgu.o): in function `<rusqlite::row::Rows as core::ops::drop::Drop>::drop':
          rusqlite.dhl4v74x-cgu.8:(.text._ZN61_$LT$rusqlite..row..Rows$u20$as$u20$core..ops..drop..Drop$GT$4drop17h5837fffe42b4404cE+0x15): undefined reference to `sqlite3_reset'
          collect2: error: ld returned 1 exit status
```

**Comment by samhh** [comment] 2020-12-28 15:08
Do you have the `sqlite` package installed? If not, give that a try.

Beyond that, aside from updating dependencies which may entail code changes, my only suggestion is to investigate [the dependency that appears to be causing the error](https://github.com/rusqlite/rusqlite).

**Comment by samhh** [comment] 2021-02-28 23:45
Might be worth giving this another try on master as I've just updated dependencies including rusqlite.

**Comment by Dialga** [comment] 2021-03-01 08:02
Unfortunately the linking stage still fails for me, however if I append `-lsqlite3 -lm` to the end of `cc` then it links properly and produces the executable.

**Comment by samhh** [comment] 2021-03-01 10:14
Hmph, okay, at least.

Given you have a workaround and the issue is likely upstreams with rusqlite I'm going to close the issue.

**Closed as completed by samhh** 2021-03-01 10:14 UTC
Labels: bug
