### ISSUE TITLE
Failed to install host for Firefox: Unrecognised operating system.

### ISSUE THREAD

**Issue by Alfaxomo** [samhh/bukubrow-host#10] opened 2019-05-06 22:07 UTC
I get the following error on step 4 of the Installation section of the readme:

bukubrow-linux-x64 --install-firefox
Failed to install host for Firefox:
	Unrecognised operating system

I also noticed during step 2 that this message was displayed:

cargo build --release --target=x86_64-unknown-linux-gnu

Thanks for any help in advance!

**Comment by Alfaxomo** [comment] 2019-05-06 22:13
Sorry, I should mention I'm running Fedora 28 with buku version 4.2.2 and bukubrow version 4.0.0.

**Comment by samhh** [comment] 2019-05-06 23:20
That step 2 text is normal, don't worry about that.

Interesting... so, [this](https://github.com/darkeld3r/os_info) library is being used to detect OS, and it says in the README that Fedora is supported. Here are some debugging steps to determine a way forward:

1. Check out the [fix-os-detection](https://github.com/SamHH/bukubrow-host/tree/fix-os-detection) branch, run the same command again and see what it logs.

2. Install `lsb-release`/`lsb_release` and see if that fixes it (I won't expect you to keep it installed, but it would be handy to know if that's the cause given that it's mentioned in that project's README). Curiously it works for me on Arch without that package installed :man_shrugging:

**Comment by Alfaxomo** [comment] 2019-05-07 01:00
1. Ok, checked out the fix-os-detection branch and tried again. It seems to know what OS and version, but still get the same error:

bukubrow-linux-x64 --install-firefox
DEBUG! os_type: Fedora
DEBUG! version: 28
Failed to install host for Firefox:
	Unrecognised operating system.

2. The relevant lsb package on Fedora is redhat-lsb so I installed that, tried on master branch and fix-os-detection branches and the same error as well.

master
Failed to install host for Firefox:
	Unrecognised operating system.

fix-os-detection
DEBUG! os_type: Fedora
DEBUG! version: 28
Failed to install host for Firefox:
	Unrecognised operating system.

I have some other distros I can try this on as well if that helps?

**Comment by samhh** [comment] 2019-05-07 08:12
Ah, looks like something I can fix, I was incorrectly assuming the library would report Fedora as a subset of Linux rather than as its own distinct entity. I should probably look to see if that logic can be simplified given the platform is known at build-time also.

I'll get on this tonight, thanks for debugging :+1:

**Comment by samhh** [comment] 2019-05-07 12:09
Hey @andrewmercerCA, I've pushed what I hope will be a fix for this issue to that same branch. I rebased so you may need to `git pull --force`. Let me know if it works! :crossed_fingers:

**Comment by Alfaxomo** [comment] 2019-05-07 16:11
@SamHH That did it, thanks!

**Closed as completed** 2019-05-07 22:26 UTC
Labels: bug

**Comment by samhh** [comment] 2019-05-07 22:41
Cheers for confirming.

This fix is merged into master and has been released as `v4.0.1`.
